### ISSUE TITLE
Why is the base xenial?

### ISSUE THREAD

**Issue by ohemorange** [basak/certbot-snap-build#30]
We should probably use a more recent version?

**Comment by bmw** [comment]
I think that's just because of the proof of concept for the externally snapped plugins is old. In the current version, it's Ubuntu 18.04 (see https://github.com/certbot/certbot/pull/7948/files#diff-5fde7a6d86053f0e1d88c0a2a238941fR18) and https://github.com/certbot/certbot/issues/7854 is tracking switching it to 20.04.
